In [1]:
import requests
import os
from pathlib import Path
from bs4 import BeautifulSoup
# text_source = "https://github.com/karpathy/char-rnn/raw/master/data/tinyshakespeare/input.txt"

In [2]:
import re
import requests
import os
from pathlib import Path
from bs4 import BeautifulSoup
# text_source = "https://github.com/karpathy/char-rnn/raw/master/data/tinyshakespeare/input.txt"
bible = open('data/bible.txt', 'r').read()
bible = BeautifulSoup(bible, "lxml").text
# Remove digits
bible = bible[165:-55]
# bible = re.sub(r'\d+.', '', bible)
# Remove brackets, 
bible = re.sub( r'\([^)]*\)', '', bible)
# Remove symbol ჲ
bible = re.sub(r'ჲ', '', bible)
bible = re.sub(r'\*', '', bible)
bible = re.sub(r'\[', '', bible)
bible = re.sub(r'\]', '', bible)
# Replace all different types of quotes with "
bible = re.sub(r'[\u201c\u201d\u201e\u201f\u2033\u2036]', '"', bible)
print(bible[:300], len(bible), bible[-300:])
text = bible

 თავდაპირველაღ ღმერთმა შექმნა ცა და მიწა. 2. მიწა იყო უსახო და უდაბური, ბნელი იდო უფსკრულზე და სული ღვთისა იძვროდა წყლებს ზემოთ. 3. თქვა ღმერთმა: იყოს ნათელი! და იქმნა ნათელი. 4. და ნახა ღმერთმა, რომ ნათელი კარგი იყო, და გაჰყარა ღმერთმა ნათელი და ბნელი. 5. ნათელს ღმერთმა უწოდა დღე და ბნელს უწოდა ღამ 4070812 ინმე რამეს მოაკლებს ამ წიგნის წინასწარმეტყველების სიტყვებს, ღმერთი მოაკლებს მას წილს სიცოცხლის ხიდან, წმიდა ქალაქიდან და იქიდან, რაც ჩაწერილია ამ წიგნში. 20. ამის დამმოწმებელი ამბობს: ჰო, მოვალ მალე! ამინ; ჰო, მოდი, უფალო იესო! 21. ჩვენი უფლის, იესო ქრისტეს მადლი ყველა თქვენგანთან. ამინ.  დასასრული.


In [3]:
len(text)

4070812

In [4]:
print(text[:1000])

 თავდაპირველაღ ღმერთმა შექმნა ცა და მიწა. 2. მიწა იყო უსახო და უდაბური, ბნელი იდო უფსკრულზე და სული ღვთისა იძვროდა წყლებს ზემოთ. 3. თქვა ღმერთმა: იყოს ნათელი! და იქმნა ნათელი. 4. და ნახა ღმერთმა, რომ ნათელი კარგი იყო, და გაჰყარა ღმერთმა ნათელი და ბნელი. 5. ნათელს ღმერთმა უწოდა დღე და ბნელს უწოდა ღამე. იყო საღამო, იყო დილა პირველი დღე. 6. თქვა ღმერთმა: იყოს წყალთა შორის მყარი და გაჰყაროს წყლები. 7. გააჩინა ღმერთმა მყარი და გაჰყარა ერთმანეთისგან წყალი, რომელიც არის მყარს ქვემოთ, და წყალი, რომელიც არის მყარს ზემოთ. და იქმნა ასე. 8. მყარს ღმერთმა უწოდა ცა. იყო საღამო, იყო დილა - მეორე დღე.  9. თქვა ღმერთმა: შეგროვდეს ერთგან ცისქვეშეთის წყალი და გამოჩნდეს ხმელეთი. და იქმნა ასე. 10. ხმელეთს ღმერთმა უწოდა მიწა და შეგროვილ წყალს უწოდა ზღვა. დაინახა ღმერთმა, რომ კარგი იყო. 11 . თქვა ღმერთმა: აღმოაცენოს მიწამ მცენარეული - ბალახი, თესლის მთესველი, ხე ნაყოფიერი, თესლოვანი ნაყოფის მომტანი მიწაზე თავისი გვარისდა მიხედვით. და იქმნა ასე. 12. წარმოშვა მიწამ მცენარეული - ბალახი, თესლის მთესველი თავისი გ

In [5]:
from collections import Counter
chars = sorted(list(set(text)))
vocab_size = len(chars)

''.join(chars), len(chars), vocab_size, Counter(text)

(' !",-.0123456789:;?აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ',
 52,
 52,
 Counter({' ': 577606,
          'ა': 508111,
          'ი': 360423,
          'ე': 293164,
          'ს': 216612,
          'მ': 198341,
          'რ': 167257,
          'დ': 161316,
          'ნ': 141570,
          'ო': 138072,
          'ვ': 136167,
          'ლ': 132852,
          'თ': 114936,
          'ბ': 92771,
          'უ': 78225,
          '.': 74428,
          'გ': 70992,
          ',': 69405,
          'ხ': 62049,
          'ც': 52705,
          'შ': 51601,
          'ყ': 34266,
          'კ': 33652,
          'ქ': 33259,
          'წ': 29784,
          'ფ': 25684,
          'ღ': 24709,
          'ტ': 23270,
          'ზ': 18245,
          'ჩ': 17185,
          '1': 16238,
          'ძ': 15938,
          '2': 11625,
          'პ': 10694,
          ':': 9018,
          '3': 7468,
          ';': 6084,
          'ჭ': 5573,
          '4': 5458,
          'ჰ': 5194,
          '-': 4962,
          'ჯ': 4861,
    

In [6]:
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda x: ''.join([itos[i] for i in x])

encode("იყო"), decode(encode("ცად"))

([27, 42, 32], 'ცად')

In [7]:
import torch

assert torch.cuda.is_available()

device = 'cuda' if torch.cuda.is_available() else "cpu"

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.min(), data.max()), device

torch.Size([4070812]) tensor(0) tensor(51)


(None, 'cuda')

In [8]:
n = int(len(data) * 0.9)
train_data = data[:n]
val_data = data[n:]

In [9]:
# block_size = 256

# train_data[:block_size+1]

In [10]:
x = train_data[:8]
y = train_data[1:8+1]
for t in range(8):
    context = x[:t+1]
    target = y[t]
    print(context, "->", target)

tensor([0]) -> tensor(26)
tensor([ 0, 26]) -> tensor(19)
tensor([ 0, 26, 19]) -> tensor(24)
tensor([ 0, 26, 19, 24]) -> tensor(22)
tensor([ 0, 26, 19, 24, 22]) -> tensor(19)
tensor([ 0, 26, 19, 24, 22, 19]) -> tensor(33)
tensor([ 0, 26, 19, 24, 22, 19, 33]) -> tensor(27)
tensor([ 0, 26, 19, 24, 22, 19, 33, 27]) -> tensor(35)


In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1337)

batch_size = 64
block_size = 256
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters=200
n_embed = 384 
n_heads = 6
n_layer = 6
dropout = 0.1

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix, ix.shape, ix.min(), ix.max(), ix.dtype)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

xb, yb = get_batch("train")
print(xb.shape, yb.shape)

torch.Size([64, 256]) torch.Size([64, 256])


In [12]:
# context = torch.zeros((1,1), device=device, dtype=torch.long)
# print(decode(m.generate(context, 100).tolist()[0]))

In [13]:
@torch.no_grad()
def estimate_loss(m: nn.Module):
    out = {}
    m.eval()
    for split in ['train', 'valid']:
        losses = torch.zeros(eval_iters)
        for i in range(eval_iters):
            xb, yb = get_batch('valid')
            _, loss = m(xb, yb)
            losses[i] = loss
        out[split] = f"Mean: {losses.mean().item():.3f}, Var: {losses.var().item():.3f}"
    return out

In [14]:
# torch.manual_seed(1337)
# B,T,C = 4,8,32 # batch, time, channel
# x = torch.randn(B,T,C)

# # Single head of SA
# # Emit q, and v
# head_size = 16
# key = nn.Linear(C, head_size, bias=False)
# query = nn.Linear(C, head_size, bias=False)
# value = nn.Linear(C, head_size, bias=False)

# # Each token emits 16 values (q, k) pairs (head size)

# k = key(x)
# print("k = ", k.var().item())

# k = k / (C ** .5) # B,T,HeadSize
# q = query(x) # B,T,HeadSize
# v = value(x)

# print("K=",k.var().item(), '1/hs^2 =',head_size ** -.5)

# # wei = torch.zeros((T,T)) # this is made from q dot v 
# wei = q @ k.permute(0,2,1) # (B,T,H) @ (B,H,T) -> (B,T,T)
# print(q.var(), k.var(), wei.var())

# tril = torch.tril(torch.ones(T,T))
# wei = wei.masked_fill(tril == 0, float('-inf'))
# wei = F.softmax(wei, dim=-1)

# out = wei @ v
# # out.shape, out
# out.shape, x.var(), out.var(), k.var(), q.var(), v.var()

In [15]:
from torch import Tensor
# batch_size = 32 * 4

class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embed, head_size, bias=False)
        self.query = nn.Linear(n_embed, head_size, bias=False)
        self.value = nn.Linear(n_embed, head_size, bias=False)
        self.register_buffer(
            'tril', torch.tril(torch.ones(block_size, block_size))
        )

        self.dropout = nn.Dropout(dropout)

    def forward(self, x: Tensor):
        B,T,C = x.shape
        k = self.key(x) # B,T,H
        q = self.query(x)
        v = self.value(x)
        wei: Tensor = q @ k.permute(0,2,1) * C ** -0.5 # B,T,T
        wei.masked_fill_(self.tril[:T,:T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        return wei @ v


class MultiHeadAttention(nn.Module):
    def __init__(self, n_heads: int, n_embed: int):
        super().__init__()
        head_size = n_embed // n_heads
        self.head_size = head_size
        self.n_heads = n_heads
        self.heads = nn.ModuleList([Head(head_size=head_size) for _ in range(n_heads)])
        self.proj = nn.Linear(n_embed, n_embed)
        self.dropout = nn.Dropout(dropout)
        # self.linear = nn.Linear(n_heads * head_size, n_embed, bias=False)

    def forward(self, x: Tensor) -> Tensor:
        x = torch.concat([h(x) for h in self.heads], dim=-1)
        x = self.proj(x)
        x = self.dropout(x)
        return x

head_size = n_embed // n_heads
h = Head(head_size=head_size)
x = torch.randn(batch_size, block_size, n_embed)
out = h(x)
print("Single head", x.shape, out.shape, head_size)

h = MultiHeadAttention(n_heads=4, n_embed=n_embed)
x = torch.randn(batch_size, block_size, n_embed)
out = h(x)
print("Multi head", x.shape, out.shape, head_size)

Single head torch.Size([64, 256, 384]) torch.Size([64, 256, 64]) 64


Multi head torch.Size([64, 256, 384]) torch.Size([64, 256, 384]) 64


In [16]:
class BatchNorm1d(nn.Module):
    def __init__(self, n_embed):
        super().__init__()
        self.eps = 1e-5
        self.gamma = nn.Parameter(torch.ones(n_embed))
        self.beta = nn.Parameter(torch.zeros(n_embed))

    def forward(self, x: Tensor) -> Tensor:
        # print(x[:,0].var(), x[:,0].shape)
        xhat = (x - x.mean(dim=0, keepdim=True)) / (x.var(dim=0, keepdim=True) + self.eps) ** .5
        xhat = xhat * self.gamma + self.beta
        # print(xhat[:,0].var(), xhat[:,0].shape)
        return xhat 
    
bn = BatchNorm1d(block_size)
x = torch.randn(batch_size, block_size)
out = bn(x)
print("BatchNorm1d", x.shape, out.shape, head_size)
print(out[0].var(), out[0].mean())
print(out[:,0].var(), out[:,0].mean())

BatchNorm1d torch.Size([64, 256]) torch.Size([64, 256]) 64
tensor(0.8527, grad_fn=<VarBackward0>) tensor(0.0648, grad_fn=<MeanBackward0>)
tensor(1.0000, grad_fn=<VarBackward0>) tensor(-7.4506e-09, grad_fn=<MeanBackward0>)


In [17]:
class FeedForward(nn.Module):
    def __init__(self, n_embed) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embed, 4 * n_embed),
            nn.ReLU(),
            nn.Linear(n_embed * 4, n_embed),
            nn.Dropout(dropout)
        )
    def forward(self, x):
        return self.net(x)

In [18]:
class Block(nn.Module):
    def __init__(self, n_embed, n_head):
        super().__init__()
        head_size = n_embed // n_head
        self.ln1 = nn.LayerNorm(n_embed)
        self.ln2 = nn.LayerNorm(n_embed)
        self.sa = MultiHeadAttention(n_heads=n_head, n_embed=n_embed)
        self.ffwd = FeedForward(n_embed=n_embed)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x
    
b = Block(n_embed=n_embed, n_head=n_heads)
x = torch.randn(32, block_size, n_embed)
x = b(x)[0]
x.var(), x.shape

(tensor(1.0690, grad_fn=<VarBackward0>), torch.Size([256, 384]))

In [23]:

class BigramLanguageModel(nn.Module):
    def __init__(self, 
                 
                 vocab_size: int,
                 n_embed: int) -> None:
        super().__init__()
        self.vocab_size = vocab_size
        self.embedding = nn.Embedding(
            vocab_size, n_embed
        )
        self.position_embedding_table = nn.Embedding(
            block_size, n_embed
        )
        # # self.sa_head = Head(n_embed)
        # self.multi_sa = MultiHeadAttention(
        #     n_heads=4,
        #     head_size=n_embed // 4,
        # ) # 4 heads, each using 8 dim qkv vectors, and later combine into 32 output vec
        # self.ffwd = FeedForward(n_embed=n_embed)
        self.blocks = nn.Sequential(
            *[Block(n_embed, n_head=4) for _ in range(n_layer)],
            # BatchNorm1d(n_embed),
            nn.LayerNorm(n_embed),
        )
        self.lm_head = nn.Linear(
            n_embed, vocab_size
        )
    def forward(self, idx: torch.Tensor, targets = None): 
        B,T = idx.shape
        pos_emb = self.position_embedding_table(
            torch.arange(T, device=device)
        ) # [T,C]
        # print_tensor("pos_emb", pos_emb)
        tok_emb = self.embedding(idx) # [B,T,C]
        # print_tensor("tok_emb", tok_emb)
        x = pos_emb + tok_emb # [B,T, n_embed]
        # print_tensor("x", x)
        # x = self.sa_head(x)
        # x = self.multi_sa(x) # [B,T, n_embed]

        # x = self.ffwd(x)
        # for b in self.blocks:
        x = self.blocks(x)
            
        # print_tensor("x (sa)", x)
        logits = self.lm_head(x) # [B,T,VocabSize]
        # print_tensor("logits", logits)
        B,T,C = logits.size()
        # wei = torch.tril(torch.ones(T,T))
        # wei = torch.masked_fill(wei == 0, float('-inf'))

        if targets is None:
            loss = None 
        else:
            loss = F.cross_entropy(
                logits.view(B*T,C), targets.view(B*T),
            )
            return logits, loss
        return logits, loss
        # return logits
    def generate(self, 
                idx, # [B, T]
                max_new_tokens: int):
        idx = idx.to(device)
        for i in range(max_new_tokens):
            # print(idx.shape, idx[:,-block_size:].shape, block_size)
            logits, loss = self(idx[:,-block_size:]) 
            logits: torch.Tensor = logits # [B,T,C]
            logits = logits[:,-1,:] # [B,C]
            probs = F.softmax(logits, dim=-1)
            next_tokens = torch.multinomial(
                probs, num_samples=1,
            )
            idx = torch.cat([idx, next_tokens], dim=1)
        # print(idx, idx.shape)
        return idx.cpu()

m = BigramLanguageModel(
    vocab_size=vocab_size, n_embed=n_embed
)
m.to(device)
opt = torch.optim.AdamW(
    m.parameters(),
    lr=learning_rate,
)
from tqdm import tqdm
import sys
for step in tqdm(range(1000 * 5), file=sys.stdout):
    xb, yb = get_batch('train')
    logits, loss  = m(xb, yb)
    loss: torch.Tensor = loss
    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()
    if step % 500 == 0:
        sys.stdout = open('stdout.txt', "a")
        print("STEP:", step, "Loss", estimate_loss(m))
        s = decode(m.generate(torch.zeros((1,1)).long(), 120)[0].tolist())
        print(s)
        sys.stdout = sys.__stdout__

100%|██████████| 5000/5000 [11:47<00:00,  7.07it/s]  


ანი ტალახაძებისა; ამიტომ ქადაგმიერება შორს მყოფნი დავითის მორჩილნი ჰყავდათ დადიმულნი და უკუნისამდენი ისრაელის წინამძღოლით. 7. გვყავდა შენი სახლი, გახდა, მაგრამ ვერაფერს შევა ჰყავდა ცისკენ, რადგან არ იცოდა შენს ძმას და არ იგულადო. გაწყდნენ შენს გულს და სიკვდილს განსდებულს, რადგან უზენაესის სიძე გამარჯვება მკერდზე. იმ დროს გაუშვა ცისკარი, დაწვა ნაღველი და მასხრის კერპება, რაც აბზია, შენს კერპთათვის არ იცოდი, როგორ შეამთხვა ეს ხალხიც. 23. მაგრამ არის ქერუბიმები, სწორი აღსავლენი და სადაც მანადისი სხური ზლიანი გ
ანი ტალახაძებისა; ამიტომ ქადაგმიერება შორს მყოფნი დავითის მორჩილნი ჰყავდათ დადიმულნი და უკუნისამდენი ისრაელის წინამძღოლით. 7. გვყავდა შენი სახლი, გახდა, მაგრამ ვერაფერს შევა ჰყავდა ცისკენ, რადგან არ იცოდა შენს ძმას და არ იგულადო. გაწყდნენ შენს გულს და სიკვდილს განსდებულს, რადგან უზენაესის სიძე გამარჯვება მკერდზე. იმ დროს გაუშვა ცისკარი, დაწვა ნაღველი და მასხრის კერპება, რაც აბზია, შენს კერპთათვის არ იცოდი, როგორ შეამთხვა ეს ხალხიც. 23. მაგრამ არის ქერუბიმები, სწორი აღსავლენი და სად

In [31]:
out = decode(
    m.generate(
        torch.tensor([encode('ანი ტალახაძე')], device=device, dtype=torch.long),
        120\
    )[0].tolist()
)
print(out)

In [32]:
torch.save(m.state_dict(), 'models/bible-georgian-6layer-384dim-5k.pt')

In [33]:
m2 = BigramLanguageModel(
    vocab_size=vocab_size, n_embed=n_embed
)
m2.load_state_dict(torch.load('models/bible-georgian-6layer-384dim-5k.pt'))
m2.eval()
m2.to(device)

BigramLanguageModel(
  (embedding): Embedding(52, 384)
  (position_embedding_table): Embedding(256, 384)
  (blocks): Sequential(
    (0): Block(
      (ln1): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (ln2): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (sa): MultiHeadAttention(
        (heads): ModuleList(
          (0-3): 4 x Head(
            (key): Linear(in_features=384, out_features=96, bias=False)
            (query): Linear(in_features=384, out_features=96, bias=False)
            (value): Linear(in_features=384, out_features=96, bias=False)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ffwd): FeedForward(
        (net): Sequential(
          (0): Linear(in_features=384, out_features=1536, bias=True)
          (1): ReLU()
          (2): Linear(in_features=1536, out_features=384, bias=True

In [48]:
out = decode(
    m2.generate(
        torch.tensor([encode('1. უბადრუკი ანი ტალახაძე ')], device=device, dtype=torch.long),
        500
    )[0].tolist()
)
# print(out)
import re
# Place newline before numbering 1,2,3
out = str(re.sub(r'(\d+)', r'\n\1', out))
print(out, file=sys.stderr)


1. უწმინდური ანი ტალახაძე და დააბრკოლებ მეფეს ტბორზე, სამუშაოდ რომ დაარწმუნეს, აშენება მეფეები.  
12. წავიდნენ ხეზერის ძეთა ტბორზე. 
13. დაიბარის ტბობიდან თითქოს დამზადებიდან მისი მტრის ძალისკენ გაძარცვავს და მკის წყალობით ამოგვიზკად იქნება. 
14. როცა ეს ქვეყანა, ეკეთება წარწერაცხმარტება ესუროს თვალს იმ გზაზე, რომელიც ესენი მათ ხორჭას, ასევე თვის სამოგენებღა და მეორე დღეს, სამოსელის მოქცეულისგან. 
15. სამარადჟამოდ დამიბრუნდა აქაბი ნეემიას ძე, დადგა ისრაელის სახლს მახლობლად. ამიტომ ასე ამბობს ყველა ხალხი, ისრაელის წიაღში იცის


In [ ]:
out = decode(
    m.generate(
        torch.tensor([encode('ანი ტალახაძე')], device=device, dtype=torch.long),
        500
    )[0].tolist()
)
print(out)