In [ ]:
import requests
import os
from pathlib import Path
from bs4 import BeautifulSoup
# text_source = "https://github.com/karpathy/char-rnn/raw/master/data/tinyshakespeare/input.txt"

In [2]:
import re

bible = open('data/bible.txt', 'r').read()
bible = BeautifulSoup(bible, "lxml").text
# Remove digits
bible = bible[165:-55]
bible = re.sub(r'\d+.', '', bible)
# Remove brackets, 
bible = re.sub( r'\([^)]*\)', '', bible)
# Remove symbol ჲ
bible = re.sub(r'ჲ', '', bible)
bible = re.sub(r'\*', '', bible)
bible = re.sub(r'\[', '', bible)
bible = re.sub(r'\]', '', bible)
# Replace all different types of quotes with "
bible = re.sub(r'[\u201c\u201d\u201e\u201f\u2033\u2036]', '"', bible)
print(bible[:300], len(bible), bible[-300:])
text = bible

 თავდაპირველაღ ღმერთმა შექმნა ცა და მიწა.  მიწა იყო უსახო და უდაბური, ბნელი იდო უფსკრულზე და სული ღვთისა იძვროდა წყლებს ზემოთ.  თქვა ღმერთმა: იყოს ნათელი! და იქმნა ნათელი.  და ნახა ღმერთმა, რომ ნათელი კარგი იყო, და გაჰყარა ღმერთმა ნათელი და ბნელი.  ნათელს ღმერთმა უწოდა დღე და ბნელს უწოდა ღამე. იყო ს 3789044 ო თუ ვინმე რამეს მოაკლებს ამ წიგნის წინასწარმეტყველების სიტყვებს, ღმერთი მოაკლებს მას წილს სიცოცხლის ხიდან, წმიდა ქალაქიდან და იქიდან, რაც ჩაწერილია ამ წიგნში.  ამის დამმოწმებელი ამბობს: ჰო, მოვალ მალე! ამინ; ჰო, მოდი, უფალო იესო!  ჩვენი უფლის, იესო ქრისტეს მადლი ყველა თქვენგანთან. ამინ.  დასასრული.


In [3]:
len(text)

3789044

In [4]:
print(text[:1000])

 თავდაპირველაღ ღმერთმა შექმნა ცა და მიწა.  მიწა იყო უსახო და უდაბური, ბნელი იდო უფსკრულზე და სული ღვთისა იძვროდა წყლებს ზემოთ.  თქვა ღმერთმა: იყოს ნათელი! და იქმნა ნათელი.  და ნახა ღმერთმა, რომ ნათელი კარგი იყო, და გაჰყარა ღმერთმა ნათელი და ბნელი.  ნათელს ღმერთმა უწოდა დღე და ბნელს უწოდა ღამე. იყო საღამო, იყო დილა პირველი დღე.  თქვა ღმერთმა: იყოს წყალთა შორის მყარი და გაჰყაროს წყლები.  გააჩინა ღმერთმა მყარი და გაჰყარა ერთმანეთისგან წყალი, რომელიც არის მყარს ქვემოთ, და წყალი, რომელიც არის მყარს ზემოთ. და იქმნა ასე.  მყარს ღმერთმა უწოდა ცა. იყო საღამო, იყო დილა - მეორე დღე.   თქვა ღმერთმა: შეგროვდეს ერთგან ცისქვეშეთის წყალი და გამოჩნდეს ხმელეთი. და იქმნა ასე.  ხმელეთს ღმერთმა უწოდა მიწა და შეგროვილ წყალს უწოდა ზღვა. დაინახა ღმერთმა, რომ კარგი იყო. . თქვა ღმერთმა: აღმოაცენოს მიწამ მცენარეული - ბალახი, თესლის მთესველი, ხე ნაყოფიერი, თესლოვანი ნაყოფის მომტანი მიწაზე თავისი გვარისდა მიხედვით. და იქმნა ასე.  წარმოშვა მიწამ მცენარეული - ბალახი, თესლის მთესველი თავისი გვარისდა მიხედვით, და ხე, 

In [5]:
from collections import Counter
chars = sorted(list(set(text)))
vocab_size = len(chars)

''.join(chars), len(chars), vocab_size, Counter(text)

(' !",-.:;?აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ',
 42,
 42,
 Counter({' ': 550556,
          'ა': 486303,
          'ი': 343975,
          'ე': 279051,
          'ს': 206772,
          'მ': 188980,
          'რ': 160018,
          'დ': 154199,
          'ნ': 134090,
          'ო': 132565,
          'ვ': 130373,
          'ლ': 126604,
          'თ': 110472,
          'ბ': 87970,
          'უ': 74252,
          'გ': 67688,
          ',': 66562,
          'ხ': 59504,
          'ც': 50926,
          'შ': 48635,
          '.': 34613,
          'ყ': 32804,
          'კ': 32372,
          'ქ': 32285,
          'წ': 28404,
          'ფ': 24203,
          'ღ': 23314,
          'ტ': 22158,
          'ზ': 17345,
          'ჩ': 15726,
          'ძ': 15225,
          'პ': 10259,
          ':': 8904,
          ';': 5649,
          'ჭ': 5357,
          'ჰ': 5085,
          '-': 4694,
          'ჯ': 4614,
          '?': 3145,
          '!': 1907,
          'ჟ': 1150,
          '"': 336}))

In [6]:
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda x: ''.join([itos[i] for i in x])

encode("იყო"), decode(encode("ცად"))

([17, 32, 22], 'ცად')

In [7]:
import torch

assert torch.cuda.is_available()

device = 'cuda' if torch.cuda.is_available() else "cpu"

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.min(), data.max()), device

torch.Size([3789044]) tensor(0) tensor(41)


(None, 'cuda')

In [65]:
n = int(len(data) * 0.9)
train_data = data[:n]
val_data = data[n:]

In [77]:
# block_size = 256

# train_data[:block_size+1]

In [68]:
x = train_data[:8]
y = train_data[1:8+1]
for t in range(8):
    context = x[:t+1]
    target = y[t]
    print(context, "->", target)

tensor([0]) -> tensor(16)
tensor([ 0, 16]) -> tensor(9)
tensor([ 0, 16,  9]) -> tensor(14)
tensor([ 0, 16,  9, 14]) -> tensor(12)
tensor([ 0, 16,  9, 14, 12]) -> tensor(9)
tensor([ 0, 16,  9, 14, 12,  9]) -> tensor(23)
tensor([ 0, 16,  9, 14, 12,  9, 23]) -> tensor(17)
tensor([ 0, 16,  9, 14, 12,  9, 23, 17]) -> tensor(25)


In [89]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1337)

batch_size = 4
block_size = 8


def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix, ix.shape, ix.min(), ix.max(), ix.dtype)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

xb, yb = get_batch("train")
print(xb.shape, yb.shape)

torch.Size([4, 8]) torch.Size([4, 8])


In [90]:
# context = torch.zeros((1,1), device=device, dtype=torch.long)
# print(decode(m.generate(context, 100).tolist()[0]))

In [91]:
eval_iters = 200
@torch.no_grad()
def estimate_loss(m: nn.Module):
    out = {}
    m.eval()
    for split in ['train', 'valid']:
        losses = torch.zeros(eval_iters)
        for i in range(eval_iters):
            xb, yb = get_batch('valid')
            _, loss = m(xb, yb)
            losses[i] = loss
        out[split] = f"Mean: {losses.mean().item():.3f}, Var: {losses.var().item():.3f}"
    return out

In [92]:
# torch.manual_seed(1337)
# B,T,C = 4,8,32 # batch, time, channel
# x = torch.randn(B,T,C)

# # Single head of SA
# # Emit q, and v
# head_size = 16
# key = nn.Linear(C, head_size, bias=False)
# query = nn.Linear(C, head_size, bias=False)
# value = nn.Linear(C, head_size, bias=False)

# # Each token emits 16 values (q, k) pairs (head size)

# k = key(x)
# print("k = ", k.var().item())

# k = k / (C ** .5) # B,T,HeadSize
# q = query(x) # B,T,HeadSize
# v = value(x)

# print("K=",k.var().item(), '1/hs^2 =',head_size ** -.5)

# # wei = torch.zeros((T,T)) # this is made from q dot v 
# wei = q @ k.permute(0,2,1) # (B,T,H) @ (B,H,T) -> (B,T,T)
# print(q.var(), k.var(), wei.var())

# tril = torch.tril(torch.ones(T,T))
# wei = wei.masked_fill(tril == 0, float('-inf'))
# wei = F.softmax(wei, dim=-1)

# out = wei @ v
# # out.shape, out
# out.shape, x.var(), out.var(), k.var(), q.var(), v.var()

In [103]:
from torch import Tensor
# batch_size = 32 * 4
n_embed = 32 
head_size = 16
n_heads = 4

class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embed, head_size, bias=False)
        self.query = nn.Linear(n_embed, head_size, bias=False)
        self.value = nn.Linear(n_embed, head_size, bias=False)
        self.register_buffer(
            'tril', torch.tril(torch.ones(block_size, block_size))
        )
    def forward(self, x: Tensor):
        B,T,C = x.shape
        k = self.key(x) # B,T,H
        q = self.query(x)
        v = self.value(x)
        wei: Tensor = q @ k.permute(0,2,1) * C ** -0.5 # B,T,T
        wei.masked_fill_(self.tril[:T,:T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        return wei @ v


class MultiHeadAttention(nn.Module):
    def __init__(self, n_heads: int, head_size: int):
        super().__init__()
        self.head_size = head_size
        self.n_heads = n_heads
        self.heads = nn.ModuleList([Head(head_size=head_size) for _ in range(n_heads)])
        self.proj = nn.Linear(n_embed, n_embed)
        # self.linear = nn.Linear(n_heads * head_size, n_embed, bias=False)

    def forward(self, x: Tensor) -> Tensor:
        x = torch.concat([h(x) for h in self.heads], dim=-1)
        x = self.proj(x)
        return x


h = Head(head_size=head_size)
x = torch.randn(batch_size, block_size, n_embed)
out = h(x)
print("Single head", x.shape, out.shape, head_size)



h = MultiHeadAttention(n_heads=4, head_size=n_embed//4)
x = torch.randn(batch_size, block_size, n_embed)
out = h(x)
print("Multi head", x.shape, out.shape, head_size)

Single head torch.Size([4, 8, 32]) torch.Size([4, 8, 16]) 16
Multi head torch.Size([4, 8, 32]) torch.Size([4, 8, 32]) 16


In [ ]:
class BatchNorm1d:
    def __init__(self):
        super().__init__()
        self.eps = 1e-5

        
    def forward(self, x: Tensor) -> Tensor:
        mean = x.mean(dim=-1, keepdim=True)
        std = x.std(dim=-1, keepdim=True) # INCORRECT
        return (x - mean) / (std + self.eps)

In [107]:
class FeedForward(nn.Module):
    def __init__(self, n_embed) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embed, 4 * n_embed),
            nn.ReLU(),
            nn.Linear(n_embed * 4, n_embed),
        )
    def forward(self, x):
        return self.net(x)

In [108]:
class Block(nn.Module):
    def __init__(self, n_embed, n_head):
        super().__init__()
        head_size = n_embed // n_head
        self.sa = MultiHeadAttention(n_heads=n_head, head_size=head_size)
        self.ffwd = FeedForward(n_embed=n_embed)
    def forward(self, x):
        x = x + self.sa(x)
        x = x + self.ffwd(x)
        return x
    
b = Block(n_embed=n_embed, n_head=n_heads)
x = torch.randn(32, block_size, n_embed)
x = b(x)[0]
x.var(), x.shape

(tensor(1.2040, grad_fn=<VarBackward0>), torch.Size([8, 32]))

In [110]:
def print_tensor(name, t: torch.Tensor):
    return
    print(name, f"{tuple(t.shape)}, m: {t.mean().item():.4f}, v: {t.var().item():.4f}")

class BigramLanguageModel(nn.Module):
    def __init__(self, 
                 
                 vocab_size: int,
                 n_embed: int) -> None:
        super().__init__()
        self.vocab_size = vocab_size
        self.embedding = nn.Embedding(
            vocab_size, n_embed
        )
        self.position_embedding_table = nn.Embedding(
            block_size, n_embed
        )
        # # self.sa_head = Head(n_embed)
        # self.multi_sa = MultiHeadAttention(
        #     n_heads=4,
        #     head_size=n_embed // 4,
        # ) # 4 heads, each using 8 dim qkv vectors, and later combine into 32 output vec
        # self.ffwd = FeedForward(n_embed=n_embed)
        self.blocks = nn.Sequential(
            Block(n_embed, n_head=4),
            Block(n_embed, n_head=4),
            Block(n_embed, n_head=4),
        )
        self.lm_head = nn.Linear(
            n_embed, vocab_size
        )
    def forward(self, idx: torch.Tensor, targets = None): 
        B,T = idx.shape
        pos_emb = self.position_embedding_table(
            torch.arange(T, device=device)
        ) # [T,C]
        # print_tensor("pos_emb", pos_emb)
        tok_emb = self.embedding(idx) # [B,T,C]
        # print_tensor("tok_emb", tok_emb)
        x = pos_emb + tok_emb # [B,T, n_embed]
        # print_tensor("x", x)
        # x = self.sa_head(x)
        # x = self.multi_sa(x) # [B,T, n_embed]

        # x = self.ffwd(x)
        # for b in self.blocks:
        x = self.blocks(x)
            
        # print_tensor("x (sa)", x)
        logits = self.lm_head(x) # [B,T,VocabSize]
        # print_tensor("logits", logits)
        B,T,C = logits.size()
        # wei = torch.tril(torch.ones(T,T))
        # wei = torch.masked_fill(wei == 0, float('-inf'))

        if targets is None:
            loss = None 
        else:
            loss = F.cross_entropy(
                logits.view(B*T,C), targets.view(B*T),
            )
            return logits, loss
        return logits, loss
        # return logits
    def generate(self, 
                idx, # [B, T]
                max_new_tokens: int):
        idx = idx.to(device)
        for i in range(max_new_tokens):
            # print(idx.shape, idx[:,-block_size:].shape, block_size)
            logits, loss = self(idx[:,-block_size:]) 
            logits: torch.Tensor = logits # [B,T,C]
            logits = logits[:,-1,:] # [B,C]
            probs = F.softmax(logits, dim=-1)
            next_tokens = torch.multinomial(
                probs, num_samples=1,
            )
            idx = torch.cat([idx, next_tokens], dim=1)
        # print(idx, idx.shape)
        return idx.cpu()

m = BigramLanguageModel(
    vocab_size=vocab_size, n_embed=n_embed
)
m.to(device)
opt = torch.optim.AdamW(
    m.parameters(),
    lr=1e-3,
)
from tqdm import tqdm
for step in range(1000 * 10):
    xb, yb = get_batch('train')
    logits, loss  = m(xb, yb)
    loss: torch.Tensor = loss
    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()
    if step % 500 == 0:
        print("STEP:", step, "Loss", estimate_loss(m))
        s = decode(m.generate(torch.zeros((1,1)).long(), 120)[0].tolist())
        print(s.replace('\n', ' '))
        # break

STEP: 0 Loss {'train': 'Mean: 3.981, Var: 0.020', 'valid': 'Mean: 3.966, Var: 0.019'}
 შჟქჭკს აჭვიჭჩბდტჭხჭფქ!ჭ!ქფ!დჭ.ჭჯზზჯძქოეტკფ ;-იტფტჩცჩ-კქაჭექ!ძყლნ!ოთხხზ!ძ"ზზეჩჭჩჩ?შჩ;ქ!ჭხღჟსჯჭ;ჯჟგთო".ჭჰფჭუსჩქჟქ!ჩზღ!ბვშ-
STEP: 500 Loss {'train': 'Mean: 2.618, Var: 0.052', 'valid': 'Mean: 2.617, Var: 0.039'}
 ღმა წაძელითნელთაგა, ჟავყიადა მათწლიყუვის ჩვისაენოთგრა ძაავერს ჭძას მოცდა ვემო კიდავანის ველოწი: სალიულძოქმება ოთდათელთდა
STEP: 1000 Loss {'train': 'Mean: 2.491, Var: 0.046', 'valid': 'Mean: 2.505, Var: 0.039'}
 ჩიხალრემდედ თარისა სი გათელინიწას მიგელი მთხვითის, მოვაპუუდ, შ უფერგი ჭ ძელეთა ტაღვათლტეტენ ჩეზემი .იდრე  იშამინს შიროდ 
STEP: 1500 Loss {'train': 'Mean: 2.471, Var: 0.054', 'valid': 'Mean: 2.465, Var: 0.049'}
 თიოს როხა მიცადებია ფაატინ: ქვეუეტელ მი, როხლწებთლა მეცს დამითულოძმებიდან ხოლიხა, თქვიდარმურმისა: ბომმეთიმ ხვერც წარიაც 
STEP: 2000 Loss {'train': 'Mean: 2.413, Var: 0.043', 'valid': 'Mean: 2.416, Var: 0.040'}
 ხაც ისა სახუი ჩომოვილიდიას დამივისგევრც ყველხატმცა მემესნქვარვანი მო! 

In [ ]:
m.position_embedding_table(
    torch.arange(1)
).shape

torch.Size([1, 32])

In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,2
tril = torch.tril(torch.ones(T,T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
xbow3

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C) # B,T,C
wei = torch.tril(torch.ones(T,T)) # T,T
wei = wei / wei.sum(1, keepdim=True) # (T,T) / (T,1) -> T,T [Row normed to 1s]
xbow2 = wei @ x # (T,T) @ (B,T,C) -> B,T,C
# torch.allclose(xbow, xbow2)

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
B,T,C = 4, 8, 2
# x = torch.arange(B*T*C).view(B,T,C).float()
# y = torch.zeros(B,T,C)
# for b in range(B):
#     for t in range(T):
#         xprev = x[b,:t+1]
#         # print("Average of", xprev.tolist(),
#         #        "on", x[b].tolist(), "To get to ", x[b,t].tolist())
#         y[b,t] = xprev.mean(dim=0)

# print(x[0])
# print(y[0])

# B,T,C = 4, 8, 2

# x = torch.randn(B,T,C) # B,T,C
x = torch.randint(0,10,(B,T,C)).float()
# xbow = x.cumsum(dim=1) / torch.ones_like(x).cumsum(1)
# xbow = x.div(T).cumsum(dim=1)

w = torch.ones(8, 8).tril() 
print(w)
w =  (1/torch.arange(1, 9)).diag() @ w
print(w)
# w = w.unsqueeze(0).repeat(B,1,1)
# xbow, w @ x[0], x[0]
x[0], w @ x[0]

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])


(tensor([[5., 7.],
         [2., 0.],
         [5., 3.],
         [5., 0.],
         [4., 0.],
         [2., 0.],
         [7., 6.],
         [0., 8.]]),
 tensor([[5.0000, 7.0000],
         [3.5000, 3.5000],
         [4.0000, 3.3333],
         [4.2500, 2.5000],
         [4.2000, 2.0000],
         [3.8333, 1.6667],
         [4.2857, 2.2857],
         [3.7500, 3.0000]]))

In [ ]:
w.shape

torch.Size([4, 3, 3])

In [ ]:
# from torch.profiler import profile, record_function, ProfilerActivity

# B,T,C = 64, 1000, 256
# x = torch.randn(B,T,C, device='cuda') # B,T,C
# # xbow = x.cumsum(dim=1) / torch.ones_like(x).cumsum(1)
# xbox = x.div(T).cumsum(dim=1)
# xbox.sum()
# assert 0

In [ ]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3)).float()
# a = torch.tensor(
#     [[1.,1.],
#      [1.,1.]]
# )
# a = torch.tensor(
#     [[1,0,1.],
#      [0,1,0.],
#      [1,0,1.],]
# )
b = torch.randint(0, 10, (3,2)).float()
# c = a @ b
# c = a @ b.T
# a,b.T,c

a,b,a@b

(tensor([[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]),
 tensor([[2., 7.],
         [6., 4.],
         [6., 5.]]),
 tensor([[ 2.,  7.],
         [ 8., 11.],
         [14., 16.]]))

In [ ]:
b.cumsum(0)

tensor([[ 2.,  7.],
        [ 8., 11.],
        [14., 16.]])

In [ ]:
torch.manual_seed(42)
a = torch.ones(3,3)
b = torch.randint(0, 10, (3,2)).float()
c = a @ b
a,b,c

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[2., 7.],
         [6., 4.],
         [6., 5.]]),
 tensor([[14., 16.],
         [14., 16.],
         [14., 16.]]))

In [ ]:
B,T,C = 4, 8, 2
x = torch.arange(B * T * C).view(B,T,C) # B,T,C
print(x, x.shape)
y = x.cumsum(dim=1) / torch.ones_like(x).cumsum(1)
print(y, y.shape)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35],
         [36, 37],
         [38, 39],
         [40, 41],
         [42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53],
         [54, 55],
         [56, 57],
         [58, 59],
         [60, 61],
         [62, 63]]]) torch.Size([4, 8, 2])
tensor([[[ 0.,  1.],
         [ 1.,  2.],
         [ 2.,  3.],
         [ 3.,  4.],
         [ 4.,  5.],
         [ 5.,  6.],
         [ 6.,  7.],
         [ 7.,  8.]],

        [[16., 17.],
         [17., 18.],
         [18., 19.],
         [19., 20.],
         [20., 21.],
         [21., 22.],
         [22., 23.],
         [23., 24.]],

        [[32., 33.],
 

In [ ]:
def linreg(x,W,b):
    return x * W + b

x = torch.tensor(1., )
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(0., requires_grad=True)
out = linreg(
    x,
    w,
    b,
)
y = torch.tensor(1.)
loss = ((out - y)).abs().sum()
print("Loss", loss, "Weight", w.item())
# loss.backward()
loss.backward()

print("Grad", w.grad.item())
w = w - w.grad

linreg(
    x,w,b
)

Loss tensor(1., grad_fn=<SumBackward0>) Weight 2.0
Grad 1.0


tensor(1., grad_fn=<AddBackward0>)